#!/bin/bash
# If /usr/local/qw/lib has been removed it means all
# the qw packages that supply libs have been removed.
# In that case remove /etc/ld.so.conf.d/linux_qw.conf
if [ ! -d /usr/local/qw/lib ] || [ -z "$(find "/usr/local/qw/lib" -maxdepth 0 -empty)" ]; then
  if [ -f /etc/ld.so.conf.d/linux-qw.conf ]; then
    rm /etc/ld.so.conf.d/linux-qw.conf
  fi
fi
ld.config